apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-javaapp-deployment
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.application.name}}
  template:
    metadata:
      labels:
        app: {{.Values.application.name}}
    spec:
      containers:
      - name: {{.Values.application.name}}
        image: {{.Values.image.repository}}
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-javaapp-service
spec:
  selector:
    app: {{.Values.application.name}}
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer