# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: new
  demands: maven


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'




- task: SonarQubePrepare@5
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: 'My_SonarQube'
    scannerMode: Other


- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: '$(Parameters.mavenPOMFile)'
    goals: '-DskipTests package sonar:sonar'

# - task: Bash@3
#   displayName: 'Run sonar:sonar'
#   inputs:
#     targetType: 'inline'
#     script: |
#       export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
#       mvn sonar:sonar   

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'poojajeeva/azurejava'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest


- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'aks'
    namespace: 'default'
    manifests: 'deployment.yaml'