# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: new
  demands: maven


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: '-DskipTests clean package'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

    
# - task: Docker@2
#   inputs:
#     containerRegistry: 'docker'
#     repository: 'azurejava'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'

# - task: Docker@0
#   displayName: 'Build an image'
#   inputs:
#     containerregistrytype: 'Container Registry'
#     dockerRegistryConnection: docker


# - task: Docker@0
#   displayName: 'Push an image'
#   inputs:
#     containerregistrytype: 'Container Registry'
#     dockerRegistryConnection: docker
#     action: 'Push an image'

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'poojajeeva/azurejava'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'