# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: new
  demands: maven


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: '-DskipTests clean package'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'poojajeeva/azurejava'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest


- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'aks'
    namespace: 'default'
    manifests: 'deployment.yaml'
    
# ... existing pipeline YAML ...

- script: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=azure-java_azurejava
  displayName: 'Run SonarCloud Analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate Result'

# ... remaining pipeline YAML ...



