

trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'mvn -B -DskipTests clean package'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


